export default {
    THEME_CHANGE: "THEME_CHANGE",
    SHOW_THEME_VIEW: "SHOW_THEME_VIEW",
    LANGUAGE_CHANGE: "LANGUAGE_CHANGE",
    SHOW_LANGUAGE_VIEW: "SHOW_LANGUAGE_VIEW",
    SHOW_LOGIN_VIEW:"SHOW_LOGIN_VIEW"
}